# Generated by Django 4.0.8 on 2022-12-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('zipcode', models.CharField(max_length=5, verbose_name='ZIP Code')),
            ],
        ),
        migrations.DeleteModel(
            name='FavoriteZipcode',
        ),
    ]
